language: php

php:
  - 5.3

before_install:
  - "git submodule update --init --recursive"

before_script:
  - "pear channel-discover pear.phing.info"
  - "pear install phing/phing"
  - "pear intsall phpunit/phpcpd"
  - "phpenv rehash"

script: "phing test"
